spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: srivatsan 
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:    show-sql: true 
    